### ISSUE TITLE
thread 'main' panicked at 'number of dynamic offsets (0) doesn't match the number of dynamic bindings in the bind group layout (2

### ISSUE THREAD

**Issue by laticoda** [ropewalker/bevy_sokoban#2] opened 2020-10-15 19:10 UTC
hello, i get this error
`thread 'main' panicked at 'number of dynamic offsets (0) doesn't match the number of dynamic bindings in the bind group layout (2)', /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:1323:35
stack backtrace:
   0:     0x55ba2a734bd0 - std::backtrace_rs::backtrace::libunwind::trace::h577ea05e9ca4629a
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55ba2a734bd0 - std::backtrace_rs::backtrace::trace_unsynchronized::h50b9b72b84c7dd56
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55ba2a734bd0 - std::sys_common::backtrace::_print_fmt::h6541cf9823837fac
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:79
   3:     0x55ba2a734bd0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf64fbff071026df5
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:58
   4:     0x55ba2a75c79c - core::fmt::write::h9ddafa4860d8adff
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/fmt/mod.rs:1082
   5:     0x55ba2a730c87 - std::io::Write::write_fmt::h1d2ee292d2b65481
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/mod.rs:1514
   6:     0x55ba2a737430 - std::sys_common::backtrace::_print::ha25f9ff5080d886d
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:61
   7:     0x55ba2a737430 - std::sys_common::backtrace::print::h213e8aa8dc5405c0
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:48
   8:     0x55ba2a737430 - std::panicking::default_hook::{{closure}}::h6482fae49ef9d963
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:200
   9:     0x55ba2a73717c - std::panicking::default_hook::he30ad7589e0970f9
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:219
  10:     0x55ba2a737a93 - std::panicking::rust_panic_with_hook::haa1ed36ada4ffb03
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:569
  11:     0x55ba2a737669 - std::panicking::begin_panic_handler::{{closure}}::h7001af1bb21aeaeb
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:476
  12:     0x55ba2a73505c - std::sys_common::backtrace::__rust_end_short_backtrace::h39910f557f5f2367
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153
  13:     0x55ba2a737629 - rust_begin_unwind
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
  14:     0x55ba2a7375db - std::panicking::begin_panic_fmt::hc1b1320af38b7e12
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:429
  15:     0x55ba29feaf48 - <core::result::Result<T,E> as wgpu::backend::direct::PrettyResult<T>>::unwrap_pretty::{{closure}}::h0ff5108623561203
  16:     0x55ba29ff7b59 - <wgpu::backend::direct::Context as wgpu::Context>::command_encoder_end_render_pass::h3fd49dfd8eacef4b
  17:     0x55ba29f8b6c4 - <bevy_wgpu::renderer::wgpu_render_context::WgpuRenderContext as bevy_render::renderer::render_context::RenderContext>::begin_pass::hc66d78ae97c1cc3e
  18:     0x55ba2a2862c3 - <bevy_render::render_graph::nodes::pass_node::PassNode<Q> as bevy_render::render_graph::node::Node>::update::hbe5a57a722fba1af
  19:     0x55ba29f92d6f - bevy_wgpu::renderer::wgpu_render_graph_executor::WgpuRenderGraphExecutor::execute::ha42598bbadbde28e
  20:     0x55ba29f8860c - bevy_wgpu::wgpu_renderer::WgpuRenderer::run_graph::hc10f921e2eb15291
  21:     0x55ba29f88b23 - bevy_wgpu::wgpu_renderer::WgpuRenderer::update::h328ad8860c87c174
  22:     0x55ba2a6f5281 - bevy_ecs::schedule::parallel_executor::ExecutorStage::run::h9687617a84ce60a2
  23:     0x55ba2a6f38d5 - bevy_ecs::schedule::parallel_executor::ParallelExecutor::run::hd465e88fc7b4fc90
  24:     0x55ba2a179ef4 - bevy_winit::winit_runner::{{closure}}::h0d7682d672301130
  25:     0x55ba2a189cbc - cart_tmp_winit::platform_impl::platform::x11::EventLoop<T>::run_return::h4ba524067a5aa1f0
  26:     0x55ba2a18a47b - cart_tmp_winit::platform_impl::platform::x11::EventLoop<T>::run::h9a330ccc71a31e30
  27:     0x55ba2a175ba2 - cart_tmp_winit::platform_impl::platform::EventLoop<T>::run::h05a36e5c4196de7c
  28:     0x55ba2a1619ea - cart_tmp_winit::event_loop::EventLoop<T>::run::hdd02c6045509e5e7
  29:     0x55ba2a166f1a - bevy_winit::run::h8ebfcbc7af57333d
  30:     0x55ba2a167104 - bevy_winit::winit_runner::h1c10ddb5ee6acf38
  31:     0x55ba2a16e9a2 - core::ops::function::Fn::call::h4fab3c618f236053
  32:     0x55ba2a6e75d6 - bevy_app::app::App::run::h1e9cc11f8da90364
  33:     0x55ba2a6e0b4a - bevy_app::app_builder::AppBuilder::run::h9d2d667a47bb6a33
  34:     0x55ba29f29b29 - bevy_sokoban::main::hd70ac7d3fbdc693a
  35:     0x55ba29eff583 - std::sys_common::backtrace::__rust_begin_short_backtrace::hebf48531a42ae7af
  36:     0x55ba29eff599 - std::rt::lang_start::{{closure}}::h18ac99cb7d5c345a
  37:     0x55ba2a737e91 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6a3209f124be2235
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:259
  38:     0x55ba2a737e91 - std::panicking::try::do_call::h88ce358792b64df0
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373
  39:     0x55ba2a737e91 - std::panicking::try::h6311c259678e50fc
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337
  40:     0x55ba2a737e91 - std::panic::catch_unwind::h56c5716807d659a1
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379
  41:     0x55ba2a737e91 - std::rt::lang_start_internal::h73711f37ecfcb277
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/rt.rs:51
  42:     0x55ba29f29c42 - main
  43:     0x7f458da680b3 - __libc_start_main
  44:     0x55ba29eec15e - _start
  45:                0x0 - <unknown>
`

**Comment by ropewalker** [comment] 2020-10-16 07:10
@laticoda This looks like https://github.com/bevyengine/bevy/issues/134 to me, but it should be fixed in the latest master that https://github.com/ropewalker/bevy_sokoban/blob/master/Cargo.toml is pointing at. I just tried to build the game, and it worked for me. Are you building from the latest revision?

**Comment by ropewalker** [comment] 2020-10-18 19:24
Closing for now, as I cannot reproduce it. Please let me know if it is still panicking for you on the latest revision.

**Closed as completed by ropewalker** 2020-10-18 19:24 UTC

**Comment by laticoda** [comment] 2020-10-19 08:29
hello, it works now you were right, excuse me to answer so late i was
traveling.
thanks for your work and sharing on github !

Le dim. 18 oct. 2020 à 21:24, Dima Lazarev <notifications@github.com> a
écrit :
